#!/bin/bash
# TekTribe Chronicles - Deployment Pipeline
# Phase 1: IONOS FTP Upload
# Phase 2: Fleek/IPFS Deploy
# Phase 3: ARweave Pin

set -e

echo "╔══════════════════════════════════════════════════════════╗"
echo "║   TEKTRIBE CHRONICLES - DEPLOYMENT PIPELINE              ║"
echo "╚══════════════════════════════════════════════════════════╝"

SITE_DIR="/c/Users/Nefs/Projects/CompendiumSite/public"
IONOS_HOST="your-ftp-host.ionos.com"
IONOS_USER="your-ftp-user"
IONOS_PASS="your-ftp-password"

# === PHASE 1: IONOS FTP UPLOAD ===
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 1: IONOS FTP UPLOAD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Uploading /public contents to IONOS web root..."
echo ""
echo "FTP Server: $IONOS_HOST"
echo "FTP User: $IONOS_USER"
echo ""
echo "Using lftp for resumable uploads:"
echo "lftp $IONOS_HOST -u $IONOS_USER,$IONOS_PASS -e 'set ftp:passive-mode yes; mirror -R $SITE_DIR /your-web-root-path; bye'"
echo ""
echo "Alternatively, use FileZilla or WinSCP to manually upload /public folder contents"
echo ""

# === PHASE 2: FLEEK/IPFS DEPLOY ===
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 2: FLEEK/IPFS DEPLOY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Install Fleek CLI"
echo "  npm install -g @fleek-platform/cli"
echo ""
echo "Step 2: Login to Fleek"
echo "  fleek login"
echo ""
echo "Step 3: Initialize new site (or select existing)"
echo "  fleek sites init"
echo ""
echo "Step 4: Deploy"
echo "  fleek sites deploy"
echo ""
echo "Note: Fleek will create an IPFS hash and provide a subdomain (e.g., site-ipfs-ipfs.io)"
echo ""

# === PHASE 3: ARWEAVE PIN ===
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 3: ARWEAVE PIN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Install ARweave CLI (if not already installed)"
echo "  npm install -g arweave-cli"
echo ""
echo "Step 2: Login to ARweave"
echo "  ar login"
echo ""
echo "Step 3: Create account (first time only)"
echo "  ar account create"
echo ""
echo "Step 4: Pin the site"
echo "  ar add $SITE_DIR --folder"
echo ""
echo "Step 5: Copy the ARweave address (e.g., 1234567890abcdef1234567890abcdef1234567890abcdef)"
echo ""
echo "Step 6: Update content/front matter with ARweave address:"
echo "  arweaveAddress = \"<YOUR_ARWEAVE_ADDRESS>\""
echo ""

# === DOMAIN MIGRATION (FUTURE) ===
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 4: DOMAIN MIGRATION (when overseer.ae is acquired)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Update baseURL in config:"
echo "  baseURL = 'https://overseer.ae'"
echo ""
echo "Step 2: Rebuild site:"
echo "  hugo --gc --minify"
echo ""
echo "Step 3: Redeploy to Fleek:"
echo "  fleek sites deploy"
echo ""
echo "Step 4: Bind custom domain in Fleek dashboard"
echo ""
echo "Step 5: Set up 301 redirect from old domain (optional):"
echo "  In Fleek dashboard: Settings → Custom Domains → Add Domain"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "DEPLOYMENT CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  [ ] Phase 1: IONOS FTP upload completed"
echo "  [ ] Phase 2: Fleek/IPFS deployment completed"
echo "  [ ] Phase 3: ARweave pinning completed"
echo "  [ ] Verify site at all three locations"
echo "  [ ] Update oracle-search with new IPFS hash"
echo "  [ ] Document ARweave address for backup"
echo ""
