baseURL = 'https://overseer.ae'
locale = 'en-us'
title = 'TekTribe Chronicles'
theme = 'Compendium'

[taxonomies]
tag = ""
category = ""

[outputs]
  home = ["HTML", "JSON"]

[params]
  author = "Æ, the Overseer"
  description = "Compendium of the Collective"
  disableRSS = true
  disableTwitter = true
  hero_banner = "images/tektribe-awakening-banner.jpg"
